### ISSUE TITLE
ERROR CheckoutFinish Subscriber getArrayCopy()

### ISSUE THREAD

**Issue by SDJeff** [PAYONE-GmbH/shopware-5#81] opened 2017-04-25 11:35 UTC
If the UST ID Validation runs to timeout because f.e. the VATID portal is not reachable, at Shopware/Plugins/Community/Core/SwagVatIdValidation/Subscriber/CheckoutFinish.php at Line 71 
you get NULL and the function fails.

`$orderDetails = Shopware()->Session()->get('sOrderVariables')->getArrayCopy();`

So the jump back to the shopware shop fails and independent if the payment was successful or not, the order is lost at the shop. Best case is payment failed too otherwise the customer paid and nobody will recognize that a new order ist there.

**Comment by fjbender** [comment] 2017-05-02 05:39
Hi @SDJeff, Sorry for the delay in getting back to you.

Is there anything you'd suggest as a workaround? Is there any exception to catch, or how can we know the external service failed?

**Comment by SDJeff** [comment] 2017-05-02 06:34
You can't know. But perhaps you can check sOrderVariables before getArrayCopy of NULL Values.
Many customer's reporting us that there are trouble with the VATID portal at the moment.

**Comment by fjbender** [comment] 2017-05-02 13:36
So how exactly should our plugin behave? If I understand correctly, this error occurs when we come back into the Shop from the payment method (e.g. PayPal), so the payment has already been authorized. I'm not sure if our plugin can do anything at this point to save the order. If so, I think this is a duplicate of #37.

**Comment by fjbender** [comment] 2017-07-10 07:58
Closed as duplicated of #37

**Closed by fjbender** 2017-07-10 07:58 UTC
